// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://vidziqmfcovvqadothnr.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InZpZHppcW1mY292dnFhZG90aG5yIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDMxMDU4MjgsImV4cCI6MjA1ODY4MTgyOH0.sdr00ncNqvMvvOrQ7sEm30ZfG7xHEX5qiIFlmDvb1LE";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);